import Link from "next/link";
import type { RouterOutputs } from "@flow-dev/api";

type Page = RouterOutputs["projects"]["list"];
export function ProjectSelector({ page }: { page: Page }) {
  if (page.items.length === 0) return <EmptyProjects />;
  return <section aria-labelledby="projects-title" className="mx-auto w-full max-w-3xl px-6 py-12"><p className="font-mono text-xs text-ink-3">CONTEXTO DO PROJETO</p><h1 id="projects-title" className="mt-3 text-3xl font-semibold tracking-tight">Escolha um projeto</h1><p className="mt-3 max-w-xl text-sm leading-6 text-ink-2">Você só vê projetos atribuídos à sua conta. O contexto escolhido fica explícito na URL.</p><ul className="mt-8 divide-y divide-line rounded-xl border border-line bg-raised">{page.items.map((project) => <li key={project.id}><Link href={`/projects/${project.id}`} className="flex items-center justify-between gap-4 px-5 py-4 hover:bg-surface focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-lane-project"><span><span className="block font-medium">{project.name}</span><span className="mt-1 block text-sm text-ink-2">{project.description ?? "Sem descrição"}</span></span>{project.isDemo && <span className="rounded-full border border-line px-2 py-1 font-mono text-xs text-ink-3">demo</span>}</Link></li>)}</ul>{page.nextCursor && <Link href={`/projects?cursor=${encodeURIComponent(page.nextCursor)}`} className="mt-4 inline-flex h-10 items-center rounded-lg border border-line px-4 text-sm hover:bg-surface">Carregar mais</Link>}</section>;
}
function EmptyProjects() { return <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col justify-center px-6 py-16"><p className="font-mono text-xs text-lane-clarify-ink">SEM PROJETO ATRIBUÍDO</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Seu espaço ainda está vazio</h1><p className="mt-4 max-w-lg text-[15px] leading-7 text-ink-2">Um administrador precisa atribuir um projeto à sua conta. Quando isso acontecer, atualize esta página para continuar.</p><Link href="/projects" className="mt-8 inline-flex h-10 w-fit items-center rounded-lg border border-line px-4 text-sm hover:bg-surface">Atualizar projetos</Link></main>; }
