export const RUN_FEEDBACK: Record<string, string> = {
  queued: "A execução aguarda o worker.",
  dispatching: "O worker está preparando o runtime.",
  running: "O agente está trabalhando no checkout selecionado.",
  waiting: "O runtime aguarda uma continuação.",
  finalizing: "O Flow Dev está salvando e validando o resultado.",
  stopping: "O pedido de cancelamento está em andamento.",
  reconciling: "O Flow Dev está confirmando o resultado no runtime.",
  succeeded: "A execução terminou com sucesso.",
  failed: "A execução terminou com falha.",
  canceled: "A execução foi cancelada.",
  blocked: "A execução foi bloqueada antes de concluir.",
  stalled: "A execução parou sem concluir.",
  exhausted: "A execução atingiu os limites configurados.",
  unknown: "O resultado ainda não foi confirmado pelo runtime.",
};

export const TERMINAL_REASON_LABELS: Record<string, string> = {
  auth_required: "A conexão precisa ser autenticada novamente.",
  provider_auth_required: "O provedor pediu uma nova autenticação da conta usada nesta execução.",
  provider_rate_limited: "O provedor recusou a execução por um limite de uso ou de requisições. Confira a mensagem recebida abaixo.",
  usage_limit_exceeded: "O Codex informou limite de uso para a conta desta execução. Confira a mensagem recebida abaixo.",
  capture_failed: "O resultado não pôde ser salvo como pacote.",
  canceled_by_author: "Cancelada a pedido da pessoa operadora.",
  catalog_stale: "O catálogo do provedor ficou desatualizado.",
  inactivity: "A execução ficou sem atividade e foi encerrada.",
  loop_version_changed: "A versão do Loop mudou durante a execução.",
  model_unavailable: "O modelo deixou de estar disponível.",
  no_op: "O runtime concluiu sem alterações.",
  outcome_unknown: "O runtime ainda não confirmou o resultado.",
  package_invalid: "Os arquivos gerados não passaram pela validação.",
  reasoning_effort_unsupported: "O nível de raciocínio não é suportado.",
  runtime_failed: "O runtime informou uma falha.",
  runtime_canceled: "O runtime cancelou a execução antes da conclusão.",
  runtime_incompatible: "O runtime não está pronto para esta execução.",
  worktree_not_ready: "O worktree não estava pronto para execução.",
  workspace_unavailable: "O CompozyOS não conseguiu abrir o projeto. Confira o arquivo .env do checkout: ele aceita apenas linhas no formato CHAVE=valor.",
};
