export const PLANNING_REQUEST_MAX_BYTES = 256 * 1024;
export const PLANNING_RESPONSE_MAX_BYTES = 256 * 1024;
export const PLANNING_TITLE_MAX_CODE_POINTS = 256;
export const PLANNING_BODY_MAX_CODE_POINTS = 65_536;
export const PLANNING_SUMMARY_MAX_CODE_POINTS = 4_000;
export const PLANNING_REASON_MAX_CODE_POINTS = 2_000;
export const PLANNING_REASONS_MAX = 20;
export const PLANNING_UNCERTAINTIES_MAX = 20;
