DROP TRIGGER IF EXISTS "task_planning_decision_immutable" ON "task_planning_decisions";
DROP TRIGGER IF EXISTS "task_planning_decision_association_guard" ON "task_planning_decisions";
DROP FUNCTION IF EXISTS "guard_task_planning_decision_insert"();
DROP FUNCTION IF EXISTS "guard_task_planning_decision"();
DROP TABLE IF EXISTS "task_planning_decisions";
DROP TRIGGER IF EXISTS "task_plan_operation_guard" ON "task_operations";
DROP FUNCTION IF EXISTS "guard_task_plan_operation"();
ALTER TABLE "task_operations" DROP CONSTRAINT IF EXISTS "task_operations_task_publication_fk";
ALTER TABLE "task_command_receipts" DROP CONSTRAINT IF EXISTS "task_command_receipts_action_check";
DROP INDEX IF EXISTS "task_operations_task_kind_created_idx";
ALTER TABLE "task_publication_attempts" DROP CONSTRAINT IF EXISTS "task_publication_attempts_task_id_id_unique";
ALTER TABLE "tasks" DROP CONSTRAINT IF EXISTS "tasks_planning_operation_fk";
ALTER TABLE "tasks" DROP CONSTRAINT IF EXISTS "tasks_id_planning_operation_unique";
ALTER TABLE "task_operations" DROP CONSTRAINT IF EXISTS "task_operations_plan_association_check";
ALTER TABLE "task_operations" DROP COLUMN IF EXISTS "input_hash";
ALTER TABLE "task_operations" DROP COLUMN IF EXISTS "publication_attempt_id";
ALTER TABLE "task_operations" DROP CONSTRAINT IF EXISTS "task_operations_kind_check";
ALTER TABLE "task_operations" ADD CONSTRAINT "task_operations_kind_check" CHECK ("kind" IN ('generate','publish'));
ALTER TABLE "tasks" DROP CONSTRAINT IF EXISTS "tasks_planning_status_check";
ALTER TABLE "tasks" DROP COLUMN IF EXISTS "planning_operation_id";
ALTER TABLE "tasks" DROP COLUMN IF EXISTS "planning_status";
