export const SPEC_REASON_MESSAGE: Record<string, string> = {
  spec_unavailable: "Esta especificação não está disponível para você.",
  planning_required: "O planejamento ainda não foi aprovado.",
  publication_required: "A Issue precisa estar publicada.",
  stage_prerequisite: "Aprove a etapa anterior antes de continuar. Nada foi iniciado.",
  route_unsupported: "A rota aprovada não passa por especificação. Nada foi iniciado.",
  package_incomplete: "O pacote está incompleto. A aprovação está indisponível.",
  decision_blocked: "Há uma decisão bloqueante em aberto. Resolva-a antes de aprovar.",
  workspace_unavailable: "O ambiente de trabalho do repositório não está disponível.",
  runtime_incompatible: "O ambiente de execução não é compatível. Nada foi iniciado.",
  runtime_unconfigured: "A execução da especificação não está configurada neste ambiente.",
  permission_out_of_scope: "Esta permissão não pode ser concedida: ela extrapola o escopo da etapa.",
  spec_conflict: "A especificação mudou. Revise a versão atual antes de tentar de novo.",
  attempt_active: "Já existe uma execução em andamento.",
  outcome_unknown: "O resultado anterior ainda não foi confirmado. Aguarde antes de tentar de novo.",
  interaction_stale: "Este pedido não está mais ativo.",
  interaction_resolved: "Este pedido já foi respondido.",
  artifact_conflict: "Os arquivos foram alterados fora do Flow Dev. Preserve a cópia externa e restaure os bytes esperados.",
  stage_approved: "Esta etapa já foi aprovada.",
  invalid_answer: "A resposta não é válida para esta pergunta.",
  invalid_permission: "O pedido de permissão está incompleto ou não confere.",
  spec_capacity: "Há muitas execuções em andamento. Tente novamente em instantes.",
  interaction_queue_full: "A fila de respostas está cheia. A resposta continua salva e pendente.",
  provider_rate_limited: "O provedor limitou as requisições. Tente novamente em instantes.",
  author_required: "Somente a pessoa operadora pode executar esta ação.",
  access_revoked: "Seu acesso a este projeto mudou.",
  request_key_reused: "Esta solicitação já foi usada com outros dados.",
  invalid_input: "Os dados enviados não são válidos.",
  context_limit: "O contexto necessário excede o limite suportado.",
  package_limit: "O pacote excede um limite suportado.",
  artifact_invalid: "Os documentos gerados são inválidos.",
  capture_failed: "Não foi possível gravar os documentos.",
  runtime_failed: "A execução falhou.",
};
