export const WORK_REASON_MESSAGE: Record<string, string> = {
  claim_required: "Ninguém reivindicou esta Issue ainda. A reivindicação é explícita e acontece na fila Ready.",
  operator_required: "Somente a pessoa operadora desta Issue pode agir.",
  claim_unresolved: "A reivindicação ainda não foi confirmada no GitHub. Nada pode ser iniciado até ela ser resolvida.",
  claimant_required: "Somente quem pediu a reivindicação pode tentar resolvê-la.",
  issue_ineligible: "A Issue não atende mais às condições de trabalho: aberta, atribuída à pessoa operadora e no quadro do projeto.",
  board_status_changed: "O status da Issue mudou no quadro do GitHub. O trabalho fica bloqueado até a coordenação ser corrigida; nada foi sobrescrito.",
  source_changed: "O texto da Issue mudou no GitHub depois do snapshot analisado. Reavalie a fonte antes de uma nova decisão ou execução.",
  machine_unavailable: "A máquina vinculada não respondeu. Abra o projeto local no seu computador e tente de novo.",
  link_unavailable: "Não há vínculo local pronto para este projeto. Configure o projeto local antes de iniciar.",
  link_changed: "O vínculo local mudou em outra sessão. Atualize a tela antes de continuar.",
  work_unavailable: "Este trabalho não existe neste projeto ou não está disponível para você.",
  invalid_cursor: "A lista mudou enquanto você navegava. Atualize para recomeçar do início.",
  repository_authorization_needed: "Entrar no Flow Dev não libera repositórios. Autorize a leitura com a sua conta do GitHub para continuar.",
  provider_rate_limited: "O GitHub limitou as consultas por agora. A fila não está vazia: tente de novo em instantes.",
  provider_unavailable: "O GitHub não respondeu. A fila não está vazia; tente de novo em instantes.",
  board_missing: "O projeto ainda não tem um quadro do GitHub configurado. Peça a uma pessoa administradora para configurá-lo.",
  ready_missing: "O quadro do projeto não tem a coluna Ready. Peça a uma pessoa administradora para ajustá-lo.",
  board_item_invalid: "O item do quadro mudou. Atualize a fila e escolha de novo.",
  in_progress_missing: "O quadro do projeto não tem a coluna In Progress. Peça a uma pessoa administradora para ajustá-lo.",
  repository_mismatch: "A Issue não pertence ao repositório deste projeto.",
  issue_unavailable: "A Issue não está mais disponível no GitHub.",
  request_key_reused: "Esta solicitação já foi usada com outros dados. Atualize a tela e tente de novo.",
  task_unavailable: "Esta tarefa não existe neste projeto ou não está disponível para você.",
  service_unavailable: "O serviço está temporariamente indisponível.",
  invalid_stored_content: "O conteúdo salvo desta tarefa não pôde ser lido com segurança. Nada foi inventado no lugar.",
};
