import { describe, expect, it } from "vitest";
import { RepositoryAuthorizationService } from "./repositoryAuthorizationService";
import { TokenCipher } from "./tokenCipher";
import { AccountMismatchError, CredentialUnavailableError, RepositoryAuthorizationNeededError } from "./repositoryErrors";
import { InMemoryRepositoryAuthorizationStore } from "../../infra/github/inMemoryRepositoryAuthorizationStore";

const key = Buffer.alloc(32, 7).toString("base64url");
const client = (id = "77") => ({ exchange: async () => ({ accessToken: "gho_test", refreshToken: "refresh", accessExpiresAt: new Date(Date.now() + 1000), refreshExpiresAt: new Date(Date.now() + 10_000), scopes: ["repo", "offline_access"] }), profile: async () => ({ id }), refresh: async () => ({ accessToken: "gho_new", refreshToken: "refresh_new", scopes: ["repo"] }) });

describe("repository authorization", () => {
  it("UT-021 stores the matching GitHub credential", async () => { const store = new InMemoryRepositoryAuthorizationStore(); const service = new RepositoryAuthorizationService(store, client(), new TokenCipher(key)); const flow = await service.begin({ userId: "u1", sessionId: "s1", returnTo: "/projects" }); await service.complete({ state: flow.state, code: "code", userId: "u1", sessionId: "s1", expectedGithubUserId: "77" }); expect((await store.findCredential("u1"))?.accessToken).toBe("gho_test"); });
  it("UT-022 rejects a different GitHub account", async () => { const store = new InMemoryRepositoryAuthorizationStore(); const service = new RepositoryAuthorizationService(store, client("88"), new TokenCipher(key)); const flow = await service.begin({ userId: "u1", sessionId: "s1", returnTo: "/projects" }); await expect(service.complete({ state: flow.state, code: "code", userId: "u1", sessionId: "s1", expectedGithubUserId: "77" })).rejects.toBeInstanceOf(AccountMismatchError); expect(await store.findCredential("u1")).toBeNull(); });
  it("UT-023 consumes state once", async () => { const service = new RepositoryAuthorizationService(new InMemoryRepositoryAuthorizationStore(), client(), new TokenCipher(key)); const flow = await service.begin({ userId: "u1", sessionId: "s1", returnTo: "/projects" }); await service.complete({ state: flow.state, code: "code", userId: "u1", sessionId: "s1" }); await expect(service.complete({ state: flow.state, code: "code", userId: "u1", sessionId: "s1" })).rejects.toThrow(); });
  it("UT-024 refreshes an expired token once", async () => { let calls = 0; const source = client(); const store = new InMemoryRepositoryAuthorizationStore(); const service = new RepositoryAuthorizationService(store, { ...source, refresh: async () => { calls++; await new Promise((resolve) => setTimeout(resolve, 1)); return source.refresh(); } }, new TokenCipher(key)); await store.saveCredential({ userId: "u1", githubUserId: "77", accessToken: "old", refreshToken: "refresh", accessExpiresAt: new Date(0), scopes: ["repo"] }); await Promise.all([service.accessToken("u1"), service.accessToken("u1")]); expect(calls).toBe(1); });
  it("UT-043 does not save a refreshed credential for a different GitHub identity", async () => { const store = new InMemoryRepositoryAuthorizationStore(); const source = client("88"); const service = new RepositoryAuthorizationService(store, source, new TokenCipher(key)); await store.saveCredential({ userId: "u1", githubUserId: "77", accessToken: "old", refreshToken: "refresh", accessExpiresAt: new Date(0), scopes: ["repo"] }); await expect(service.accessToken("u1")).rejects.toBeInstanceOf(AccountMismatchError); expect((await store.findCredential("u1"))?.accessToken).toBe("old"); });
  it("UT-025 fails closed when refresh is unavailable", async () => { const store = new InMemoryRepositoryAuthorizationStore(); const service = new RepositoryAuthorizationService(store, { ...client(), refresh: async () => { throw new Error("secret refresh"); } }, new TokenCipher(key)); await store.saveCredential({ userId: "u1", githubUserId: "77", accessToken: "old", refreshToken: "refresh", accessExpiresAt: new Date(0), scopes: ["repo"] }); await expect(service.accessToken("u1")).rejects.toBeInstanceOf(RepositoryAuthorizationNeededError); });
  it("UT-026 and UT-027 encrypts and rejects tampered credentials", () => { const cipher = new TokenCipher(key); const encrypted = cipher.encrypt("gho_test"); expect(encrypted).not.toContain("gho_test"); expect(cipher.decrypt(encrypted)).toBe("gho_test"); expect(() => cipher.decrypt(encrypted + "x")).toThrow(CredentialUnavailableError); });
});
